### ISSUE TITLE
Plugin ZIP file structure has been changed again

### ISSUE THREAD

**Issue by dinkumoil** [Hsilgos/nppsaveasadmin#15]
Since the author of Notepad++ has changed the requirements for the internal structure of plugin ZIP files ([see here](https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready/32)) your current ZIP package is no longer valid and will not install properly.

**Comment by chcg** [comment]
@Hsilgos Thanks for providing this official version. I archived mine repo in favour of this one.
Would you like to update
https://npppm.bruderste.in/plugins/view/save-as-admin
to this repo here or should I do it for you and then take it over to https://github.com/bruderstein/npp-plugins-x64, so the old PluginManager also knows about it.

**Comment by Hsilgos** [comment]
> @Hsilgos Thanks for providing this official version. I archived mine repo in favour of this one.
> Would you like to update
> https://npppm.bruderste.in/plugins/view/save-as-admin
> to this repo here or should I do it for you and then take it over to https://github.com/bruderstein/npp-plugins-x64, so the old PluginManager also knows about it.

Unfortunately i don't have access to npppm.bruderste.in anymore and author doesn't respond, so i would appreciate if you can do it.
And thank you for your work to migrate old version to x64 and Appveyor, it was usable for my version.

**Comment by timea-techgirl** [comment]
Is this the cause of plugin not working in latest npp?

**Comment by chcg** [comment]
@timeakesmarky  Latest N++ is which version 7.7? In this case the underlying version of scintilla changed from 3.5.6 -> 4.1.4 and something might be needed to be adapted within this plugin.

**Comment by Hsilgos** [comment]
Checked changes in latest version, there are nothing what could break plugin.
I'm continue investigating.

**Comment by Hsilgos** [comment]
@timeakesmarky , 
I checked it on Notepad++ 7.7 x64 and it works. I haven't found changes in latest Scintilla which could break plugin.
Could you describe:
1. your environment: OS (including architecture x86/x64), Notepad++ version (including architecture x86/x64)
2. What are you trying to do
3. Expected behavior
4. Actual behavior

**Comment by timea-techgirl** [comment]
Yes, v7.7 x64. The plugin didn't work for me even in 7.6.4 which I previously had. I just updated to test it. It has worked for me magically at rare occasions but 99 percent of the times, it doesn't.

OS Info:
I'm running Windows 10 LTSC 2019 x64, Notepad++ v7.7 x64.

What I did:
I get the administrator prompt when I press Ctrl + S and when I click "Yes", I get this:
**The file cannot be saved and it may be protected.
Do you want to launch Notepad++ in Administrator mode?**

Expected Behaviour:
The file must get saved instead of failing. I just tried it on hosts file and got the same error.

**Comment by Hsilgos** [comment]
@timeakesmarky , it looks like plugin works (because the administration prompt appears), but permissions which are granted are not enough...
Could you answer next few questions?
1. How many users with administration permissions are registered on your computer?
2. Is Notepad++ able to save the same file if you run it in Administration mode as it asks?
3. Where are you trying to save file? Is it some system folder? Or just protected?

I think I can add option to choose user account to save file with if it can help, but firstly I need to understand problem.

**Comment by timea-techgirl** [comment]
Oh I see. I'm the administrator and my account has admin privileges. It's my personal computer. And there's one non-admin user account.

Yes, notepad++ saves it fine when it runs in admin mode.

I'm trying to save with Ctrl + S, so it's the same location as the file. For example, hosts file in system32/drivers/etc/hosts

**Comment by timea-techgirl** [comment]
@Hsilgos One thing, my notepad++ is portable and I have it unpacked on D drive and I use it with a desktop shortcut.

**Comment by dinkumoil** [comment]
I was facing the same problem when I updated to _NppSaveAsAdmin_ v1.0.172. The reason was my AV software (Avira Anti Virus Free). It blocked the temporary DLL file the plugin creates in the `%TEMP%` folder and even remembered this for the whole remaining Windows session. I had to reboot and deactivate Avira to be able to use the plugin.

Thus, I reverted to _NppSaveAsAdmin_ v1.0.0.3 from [>>> the old SourceForge repo <<<](https://sourceforge.net/projects/nppsaveasadmin/files/).

I guess at the time when I've tried _NppSaveAsAdmin_ v1.0.172, Avira had white-listed the old plugin version but not the new one. This was more than half a year ago, I don't know the current state of white-listing. I still use v1.0.0.3 and it works fine (Windows 7 x64 and Windows 10 Prof. v1809 x64, Notepad++ v7.5.6 x86).

**Comment by timea-techgirl** [comment]
Yes, I thought so too.
Disabling kaspersky fixed the issue. I will try adding the plugin to kaspersky exceptions and see if it works.

**Comment by timea-techgirl** [comment]
Oh, I see I have already added it to exclusions but it's running from temp directory which is the cause of the issue.

Now I added the temp location and issue fixed.

@Hsilgos If it's possible, let the exe be extracted to the same directory.

**Comment by Hsilgos** [comment]
@timeakesmarky , @dinkumoil 
Great that issue is detected, thank you both for investigation. I should figure out how to solve it. Yes, it's possible to run app from the same folder if it's not protected itself. The app can be even unpacked there already at installation time. I wanted to avoid that because of some security thoughts, but i guess that i can protect it differently (it's even necessary to do this).

**Comment by dinkumoil** [comment]
@timeakesmarky 

I would **highly** recommend to remove your `%TEMP%` folder from Kaspersky's exception list. Malware uses this folder as well. Better try to use the old plugin version (see link in my posting above) as long as @Hsilgos hasn't provided another fix.

**Comment by timea-techgirl** [comment]
@dinkumoil Oh yes, I know. I have just added the NppAdminAccess.exe file to the exclusions, not the temp directory itself. :)

**Comment by Hsilgos** [comment]
@timeakesmarky , @dinkumoil , I prepared version with static file, may be it will keep antiviruses calm. 
You can try it, I didn't publish it in plugin manager yet: https://github.com/Hsilgos/nppsaveasadmin/releases/tag/1.0.190

**Comment by timea-techgirl** [comment]
Thanks, works without adding the temp file name to exclusions.
But still not friendly with antivirus. Tried removing notepad folder from exclusions and save fails.

**Comment by dinkumoil** [comment]
I didn't install the updated plugin (because v1.0.0.3 works fine for me) but I checked _NppAdminAccess.exe_ and _NppSaveAsAdmin.dll_ with Avira - no warning, considered to be clean.

**Comment by timea-techgirl** [comment]
Kaspersky reports it clean as well but it still interferes in the job and fails the save. I have reported the file as false-positive. If an agent answers me, I'll get the problem solved.

**Comment by Hsilgos** [comment]
@timeakesmarky , has agent answered you?
@dinkumoil , There is a good reason to use new version: it supports "Save as..." operation. Old one doesn't.

**Comment by timea-techgirl** [comment]
Oh no, I didn't get any answer. I just reported it again. If I don't get an answer, I'll contact customer support.

**Comment by dinkumoil** [comment]
@Hsilgos 

I have tested _NppSaveAsAdmin_ v1.0.195 with Notepad++ v7.5.6 and _Avira Antivirus_. It worked very well, no malware warning.

Thank you for supporting _Save as_ operation, very useful feature.

BTW: The initial reason why I've opened this issue (changes in plugin ZIP file structure required) no longer exists. I think you could close this issue.

**Comment by timea-techgirl** [comment]
@Hsilgos I contacted Kaspersky personally about this and they told me to add it to exclusions. I insisted that Kaspersky shouldn't block clean files from working without even notifying. The file is clean in a scan, it just doesn't save. They've taken my request.

Now the issue can be closed. :) Thanks for your contribution and kindness. :)
